---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: mig-hook-runner
  namespace: test
subjects:
  - kind: ServiceAccount
    namespace: openshift-migration 
    name: mig-hook-runner
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
